# Generated by Django 5.2.7 on 2025-11-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'مرد'), ('f', 'زن'), ('n', 'نمی\u200cخواهم مشخص کنم')], max_length=10, null=True),
        ),
    ]
